Repository phpList/core, pull requests merged in 2018-02, with the labels that each got.

#263 [TASK] Add changelog entries for changes since 4.0.0-alpha1
  CHANGELOG.md
Labels: documentation

#264 [TASK] Trait for database test, base class for web tests
  CHANGELOG.md
  Classes/TestingSupport/AbstractWebTest.php
  Classes/TestingSupport/Fixtures/TouchTable.csv
  Classes/TestingSupport/Traits/DatabaseTestTrait.php
  Configuration/PHPMD/rules.xml
  Tests/Integration/Domain/Repository/Identity/AdministratorRepositoryTest.php
  Tests/Integration/Domain/Repository/Identity/AdministratorTokenRepositoryTest.php
  Tests/Integration/Domain/Repository/Messaging/SubscriberListRepositoryTest.php
  Tests/Integration/Domain/Repository/Subscription/SubscriberRepositoryTest.php
  Tests/Integration/Domain/Repository/Subscription/SubscriptionRepositoryTest.php
  Tests/Integration/EmptyStartPageBundle/Controller/DefaultControllerTest.php
  Tests/Integration/Security/AuthenticationTest.php
Labels: cleanup, enhancement

#265 [CLEANUP] Rename the Tests/ directory to tests/
  .github/CONTRIBUTING.md
  .github/PULL_REQUEST_TEMPLATE.md
  .travis.yml
  CHANGELOG.md
  Documentation/ClassStructure.md
  composer.json
  tests/Integration/Composer/ScriptsTest.php
  tests/Integration/Core/ApplicationKernelTest.php
  tests/Integration/Core/ApplicationStructureTest.php
  tests/Integration/Core/BootstrapTest.php
  tests/Integration/Domain/Repository/Fixtures/Administrator.csv
  tests/Integration/Domain/Repository/Fixtures/AdministratorTokenWithAdministrator.csv
  tests/Integration/Domain/Repository/Fixtures/DetachedAdministratorTokens.csv
  tests/Integration/Domain/Repository/Fixtures/Subscriber.csv
  tests/Integration/Domain/Repository/Fixtures/SubscriberList.csv
  tests/Integration/Domain/Repository/Fixtures/Subscription.csv
  tests/Integration/Domain/Repository/Identity/AdministratorRepositoryTest.php
  tests/Integration/Domain/Repository/Identity/AdministratorTokenRepositoryTest.php
  tests/Integration/Domain/Repository/Messaging/SubscriberListRepositoryTest.php
  tests/Integration/Domain/Repository/Subscription/SubscriberRepositoryTest.php
  tests/Integration/Domain/Repository/Subscription/SubscriptionRepositoryTest.php
  tests/Integration/EmptyStartPageBundle/Controller/DefaultControllerTest.php
  tests/Integration/Routing/ExtraLoaderTest.php
  tests/Integration/Security/AuthenticationTest.php
  tests/Integration/Security/HashGeneratorTest.php
  tests/Support/Interfaces/TestMarker.php
  tests/System/ApplicationBundle/PhpListApplicationBundleTest.php
  tests/Unit/Composer/ModuleFinderTest.php
  tests/Unit/Composer/PackageRepositoryTest.php
  tests/Unit/Composer/ScriptHandlerTest.php
  tests/Unit/Core/ApplicationKernelTest.php
  tests/Unit/Core/ApplicationStructureTest.php
  tests/Unit/Core/BootstrapTest.php
  tests/Unit/Core/EnvironmentTest.php
  tests/Unit/Domain/Model/Identity/AdministratorTest.php
  tests/Unit/Domain/Model/Identity/AdministratorTokenTest.php
  tests/Unit/Domain/Model/Messaging/SubscriberListTest.php
  tests/Unit/Domain/Model/Subscription/SubscriberTest.php
  tests/Unit/Domain/Model/Subscription/SubscriptionTest.php
  tests/Unit/Domain/Repository/Identity/AdministratorRepositoryTest.php
  tests/Unit/Domain/Repository/Identity/AdministratorTokenRepositoryTest.php
  tests/Unit/Domain/Repository/Messaging/SubscriberListRepositoryTest.php
  tests/Unit/Domain/Repository/Subscription/SubscriberRepositoryTest.php
  tests/Unit/Domain/Repository/Subscription/SubscriptionRepositoryTest.php
  tests/Unit/EmptyStartPageBundle/Controller/DefaultControllerTest.php
  tests/Unit/EmptyStartPageBundle/PhpListEmptyStartPageBundleTest.php
  tests/Unit/Routing/ExtraLoaderTest.php
  tests/Unit/Security/AuthenticationTest.php
  tests/Unit/Security/HashGeneratorTest.php
Labels: cleanup

#267 [CLEANUP] Remove the pre-rewrite core classes
  .github/CONTRIBUTING.md
  .travis.yml
  CHANGELOG.md
  composer.json
  core/.gitignore
  core/Admin.php
  core/Attachment.php
  core/Bounce.php
  core/BounceProcessor.php
  core/Campaign.php
  core/Config.php
  core/EmailUtil.php
  core/Entity/AdminEntity.php
  core/Entity/CampaignEntity.php
  core/Entity/ListEntity.php
  core/Entity/SubscriberEntity.php
  core/Entity/TemplateEntity.php
  core/Entity/TemplateImageEntity.php
  core/ListManager.php
  core/Model/AdminModel.php
  core/Model/ListModel.php
  core/Model/SubscriberModel.php
  core/Pass.php
  core/QueueProcessor.php
  core/README.md
  core/SubscriberManager.php
  core/Template.php
  core/TemplateImage.php
  core/helper/Cache.php
  core/helper/Database.php
  core/helper/Language.php
  core/helper/Logger.php
  core/helper/Logger/DatabaseWriter.php
  core/helper/Logger/FileWriter.php
  core/helper/Logger/LoggerWriter.php
  core/helper/Logger/LoggerWriterAbstractFactory.php
  core/helper/Logger/NotSuchWriterException.php
  core/helper/PrepareCampaign.php
  core/helper/Process.php
  core/helper/Session.php
  core/helper/Shortcuts.php
  core/helper/StringClass.php
  core/helper/Timer.php
  core/helper/Util.php
  core/interfaces/EmailAddressInterface.php
  core/interfaces/PasswordInterface.php
  core/phpList.php
  core/phpListMailer.php
  core/services.yml
  core/tests/EmailUtilTest.php
  core/tests/PassTest.php
Labels: cleanup

#268 [CLEANUP] Rename Classes/ to src/
  .github/CONTRIBUTING.md
  .github/PULL_REQUEST_TEMPLATE.md
  .travis.yml
  CHANGELOG.md
  Configuration/config.yml
  Configuration/services.yml
  README.md
  composer.json
  src/Composer/ModuleFinder.php
  src/Composer/PackageRepository.php
  src/Composer/ScriptHandler.php
  src/Core/ApplicationKernel.php
  src/Core/ApplicationStructure.php
  src/Core/Bootstrap.php
  src/Core/Environment.php
  src/Domain/Model/Identity/Administrator.php
  src/Domain/Model/Identity/AdministratorToken.php
  src/Domain/Model/Interfaces/CreationDate.php
  src/Domain/Model/Interfaces/Identity.php
  src/Domain/Model/Interfaces/ModificationDate.php
  src/Domain/Model/Messaging/SubscriberList.php
  src/Domain/Model/Subscription/Subscriber.php
  src/Domain/Model/Subscription/Subscription.php
  src/Domain/Model/Traits/CreationDateTrait.php
  src/Domain/Model/Traits/IdentityTrait.php
  src/Domain/Model/Traits/ModificationDateTrait.php
  src/Domain/Repository/AbstractRepository.php
  src/Domain/Repository/Identity/AdministratorRepository.php
  src/Domain/Repository/Identity/AdministratorTokenRepository.php
  src/Domain/Repository/Messaging/SubscriberListRepository.php
  src/Domain/Repository/Subscription/SubscriberRepository.php
  src/Domain/Repository/Subscription/SubscriptionRepository.php
  src/EmptyStartPageBundle/Controller/DefaultController.php
  src/EmptyStartPageBundle/PhpListEmptyStartPageBundle.php
  src/Routing/ExtraLoader.php
  src/Security/Authentication.php
  src/Security/HashGenerator.php
  src/TestingSupport/AbstractWebTest.php
  src/TestingSupport/Fixtures/TouchTable.csv
  src/TestingSupport/Traits/ContainsInstanceAssertionTrait.php
  src/TestingSupport/Traits/DatabaseTestTrait.php
  src/TestingSupport/Traits/ModelTestTrait.php
  src/TestingSupport/Traits/SimilarDatesAssertionTrait.php
  src/TestingSupport/Traits/SymfonyServerTrait.php
Labels: cleanup

#270 [CLEANUP] Rename web/ to public/
  .github/CONTRIBUTING.md
  .travis.yml
  CHANGELOG.md
  README.md
  composer.json
  public/.htaccess
  public/app.php
  public/app_dev.php
  public/app_test.php
  public/favicon-180.png
  public/favicon-48.png
  public/favicon.ico
  src/Composer/ScriptHandler.php
  src/TestingSupport/Traits/SymfonyServerTrait.php
Labels: cleanup

#269 [CLEANUP] Rename Documentation/ to docs/
  README.md
  docs/ClassStructure.md
  docs/DomainModel/DomainModel.dot
  docs/DomainModel/DomainModel.svg
  docs/DomainModel/Entities.md
  docs/structure.md
Labels: cleanup

#271 [BUGFIX] Cascading removal of subscriptions
  CHANGELOG.md
  src/Domain/Model/Messaging/SubscriberList.php
  src/Domain/Model/Subscription/Subscriber.php
  tests/Integration/Domain/Repository/Messaging/SubscriberListRepositoryTest.php
  tests/Integration/Domain/Repository/Subscription/SubscriberRepositoryTest.php
Labels: bug

#272 [FOLLOWUP] Use correct association count in tests for cascading removal
  CHANGELOG.md
  tests/Integration/Domain/Repository/Messaging/SubscriberListRepositoryTest.php
  tests/Integration/Domain/Repository/Subscription/SubscriberRepositoryTest.php
Labels: bug

#277 [BUGFIX] Fix Composer-related build failure with PHP 7
  composer.json
Labels: bug

#274 [FEATURE] Interface for domain models
  CHANGELOG.md
  src/Domain/Model/Identity/Administrator.php
  src/Domain/Model/Identity/AdministratorToken.php
  src/Domain/Model/Interfaces/DomainModel.php
  src/Domain/Model/Messaging/SubscriberList.php
  src/Domain/Model/Subscription/Subscriber.php
  src/Domain/Model/Subscription/Subscription.php
  src/Domain/Repository/AbstractRepository.php
  tests/Unit/Domain/Model/Identity/AdministratorTest.php
  tests/Unit/Domain/Model/Identity/AdministratorTokenTest.php
  tests/Unit/Domain/Model/Messaging/SubscriberListTest.php
  tests/Unit/Domain/Model/Subscription/SubscriberTest.php
  tests/Unit/Domain/Model/Subscription/SubscriptionTest.php
Labels: cleanup, enhancement

#275 Change the package name to phplist/core
  CHANGELOG.md
  README.md
  composer.json
  src/Composer/ModuleFinder.php
  src/Composer/ScriptHandler.php
  src/Core/ApplicationKernel.php
  src/Core/ApplicationStructure.php
  src/Core/Bootstrap.php
  tests/Integration/Composer/ScriptsTest.php
  tests/Support/Interfaces/TestMarker.php
  tests/Unit/Composer/ModuleFinderTest.php
  tests/Unit/Composer/PackageRepositoryTest.php
  tests/Unit/Composer/ScriptHandlerTest.php
Labels: cleanup

#278 [FEATURE] Repository.remove
  CHANGELOG.md
  src/Domain/Repository/AbstractRepository.php
  tests/Integration/Domain/Repository/Identity/AdministratorRepositoryTest.php
  tests/Integration/Domain/Repository/Identity/AdministratorTokenRepositoryTest.php
  tests/Integration/Domain/Repository/Messaging/SubscriberListRepositoryTest.php
  tests/Integration/Domain/Repository/Subscription/SubscriberRepositoryTest.php
  tests/Integration/Domain/Repository/Subscription/SubscriptionRepositoryTest.php
Labels: enhancement

#279 [CLEANUP] Drop obsolete configuration and documentation files
  Configuration/config.ini.dist
  Configuration/phpunit.example.xml
  docs/ClassStructure.md
  docs/structure.md
Labels: cleanup

#280 [META] Add Sam Tuke as package developer
  composer.json
Labels: meta

#282 [CLEANUP] Use Repository.remove when testing cascading removal
  tests/Integration/Domain/Repository/Messaging/SubscriberListRepositoryTest.php
  tests/Integration/Domain/Repository/Subscription/SubscriberRepositoryTest.php
Labels: cleanup

#283 [CLEANUP] Move the PHPUnit configuration file
  .github/CONTRIBUTING.md
  .travis.yml
  CHANGELOG.md
  phpunit.xml.dist
Labels: cleanup

#284 [FEATURE] SubscriptionRepository.findOneBySubscriberListAndSubscriber
  CHANGELOG.md
  src/Domain/Repository/Subscription/SubscriptionRepository.php
  tests/Integration/Domain/Repository/Fixtures/Subscriber.csv
  tests/Integration/Domain/Repository/Subscription/SubscriptionRepositoryTest.php
Labels: enhancement

#285 [CLEANUP] Move the database schema to resources/
  .github/CONTRIBUTING.md
  .travis.yml
  CHANGELOG.md
  README.md
  resources/Database/Schema.sql
  resources/Database/phplist db.mwb
Labels: cleanup

#286 [CLEANUP] Reduce the number of Doctrine-related imports
  src/Domain/Model/Identity/Administrator.php
  src/Domain/Model/Identity/AdministratorToken.php
  src/Domain/Model/Interfaces/ModificationDate.php
  src/Domain/Model/Messaging/SubscriberList.php
  src/Domain/Model/Subscription/Subscriber.php
  src/Domain/Model/Subscription/Subscription.php
  src/Domain/Model/Traits/IdentityTrait.php
  src/Domain/Model/Traits/ModificationDateTrait.php
Labels: cleanup

#289 [CLEANUP] Fix some Scrutinizer warnings
  src/Composer/ModuleFinder.php
  src/Composer/ScriptHandler.php
  src/Core/Bootstrap.php
  src/Core/Environment.php
  src/Domain/Repository/Identity/AdministratorTokenRepository.php
Labels: cleanup
